version: 2
jobs:
  build:
    working_directory: /root/jelly_shot
    docker:
      - image: elixir:1.4.0
    steps:
      - checkout
      - run:
          name: Install hex & rebar
          command: mix local.hex --force && mix local.rebar --force
      - run:
          name: Install Phoenix
          command: mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
      - run:
          name: Install dependencies
          command: mix deps.get
      - run:
          name: Test
          command: MIX_ENV=test mix do compile, coveralls.json && bash <(curl -s https://codecov.io/bash)
